### PR TITLE
Pr branch：#3 Repetitive Code to Run/Execute Each Language

### PR DESCRIPTION
**Pull request by akira-cn**
Repost this PR and remove WebSocket support.

### CODE REVIEW

**Review by YasserDbeis — APPROVED** [review]
Roughly tested some languages and reviewed the code. Looks good. Kudos for the custom timeout addition.

**Comment by YasserDbeis** [comment]
> Roughly tested some languages and reviewed the code. Looks good. Kudos for the custom timeout addition.

Messing with this pr exposed our need for a test suite.

**Comment by Jaagrav** [comment]
@YasserDbeis so this is ready to merge?

**Comment by YasserDbeis** [comment]
> @YasserDbeis so this is ready to merge?

Yeah

**Pull request merged**
